name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_backend:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'e21205b207c3ff031906575712edab6f13eb0b361f2085f1f1237b7126d785e826a450292b6cfd1d64d92e6563bbde02') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer
          alias composer='/usr/local/bin/composer'

      - name: Install dependencies and build
        run: |
          cd back
          cp .env.example .env
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan key:generate

      - name: Cache vendor directory
        uses: actions/cache@v2
        with:
          path: back/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('app/back/composer.lock') }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifact
          path: back/vendor

  test_backend:
    runs-on: debian-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'

      - name: Install dependencies
        run: |
          cd back
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: |
          cd back
          vendor/bin/phpunit ./tests/Unit

  deploy:
    runs-on: debian-latest
    needs: [build_backend, test_backend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: backend-artifact
          path: back/vendor

      - name: Deploy
        # Add your deployment steps here
        run: echo "Deploying..."

      # Add more deployment steps if necessary
