name: front

on:
  push:
    branches:
      - master
        #    paths:
        #      - 'back/**'
        #    pull_request:
        #      branches:
        #        - master
        #      paths:
        #        - 'back/**'

jobs:
  build_front:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update package lists
      run: sudo apt-get update

    - name: Install required packages
      run: |
        sudo apt-get install -y build-essential curl git

    - name: Use Node.js 14.x
      uses: actions/setup-node@v4
      with:
          node-version: 14.x
          
    - name: Download Python 2.7
      run: wget https://www.python.org/ftp/python/2.7/Python-2.7.tgz -P ~/

    - name: Extract Python 2.7
      run: tar -xzf ~/Python-2.7.tgz -C ~/

    - name: Configure and install Python 2.7
      run: |
        cd ~/Python-2.7
        ./configure && make && sudo make install

    - name: Install Node.js dependencies
      run: npm install
      working-directory: ./front

    - name: Build
      run: npm run build
      working-directory: ./front

    - name: Install Yarn
      run: npm install -g yarn
      working-directory: ./front

    - name: remove node_modules
      run: rm -rf node_modules/
      working-directory: ./front

    - name: install yarn packages
      run: yarn install
      working-directory: ./front

    - name: Unit tests
      run: yarn run test
      working-directory: ./front
