name: front ci / cd

on:
  push:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install dependencies and build frontend
        run: |
          sudo apt update -qy
          sudo apt install wget npm -qy
          npm install -g @angular/cli@7.1.4 --silent
          wget https://github.com/nvm-sh/nvm/archive/refs/tags/v0.33.10.tar.gz
          tar -xvf ./v0.33.10.tar.gz
          rm -rf ./v0.33.10.tar.gz
          cd ./nvm-0.33.10
          ./install.sh
          cd ..
          rm -rf ./nvm-0.33.10
          source ~/.nvm/nvm.sh
          nvm install 14.21.3
          wget https://www.python.org/ftp/python/2.7.17/Python-2.7.17.tar.xz
          tar -xvf ./Python-2.7.17.tar.xz
          rm -rf ./Python-2.7.17.tar.xz
          cd Python-2.7.17
          ./configure && make && sudo make install
          cd ..
          rm -rf ./Python-2.7.17
          cd front
          npm install
          npm run build:prod
        working-directory: ./front
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-artifact
          path: ./front/dist

  test_frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -qy

      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact
          path: ./front/dist
      
      - name: Run frontend tests
        run: npm run test
        working-directory: ./front

  deploy_frontend:
    runs-on: self-hosted
    needs: [build_frontend, test_frontend]
    steps:
      - name: Deployment step
        run: echo "Deploying..."
